//Created by ChrisMoody on 11/1/2014
//Bar Color Based on Above/Below EMA...
study(title = "CM_EMA Trend Bars", shorttitle="CM_EMA TrendBars",overlay=true)
ema1 = input(34, minval=1, maxval=300, title="EMA UpTrend")
shema = input(true, title="Show EMA Trend is Based On?")

usedEma = ema(close, ema1)

emaUpColor() => hlc3 >= usedEma
emaDownColor() => hlc3  < usedEma

col = hlc3  >= usedEma ? lime : hlc3  < usedEma ? red : white

barcolor(emaUpColor() ? lime: emaDownColor() ? red : na)
plot(shema and usedEma ? usedEma : na, title="EMA", style=line, linewidth=3, color=col)