//@version=5
indicator(title="CM_EMA Trend Bars", shorttitle="CM_EMA TrendBars", overlay=true, timeframe = "", timeframe_gaps = true)

ema1 = input(20, title="EMA UpTrend")
shema = input(true, title="Show EMA Trend is Based On?")
atrPeriod = input.int(10, "ATR Length", minval = 1)
factor = input.float(4.0, "Factor", minval = 0.01, step = 0.01)

usedEma = ta.ema(close, ema1)
[supertrend, direction] = ta.supertrend(factor, atrPeriod)

var upCount = 0
var downCount = 0

isUpTrend = direction < 0 and direction[1] >= 0
isDownTrend = direction > 0 and direction[1] <= 0

if (hlc3 >= usedEma)
    upCount := upCount + 1 
    downCount := 0

if (hlc3 < usedEma)
    downCount := downCount + 1
    upCount := 0

emaUp = upCount >= 2
emaDown = downCount >= 2

buy = emaUp and isUpTrend
sell = emaDown and isDownTrend
closePosition = (upCount == 1 and direction > 0) or (downCount == 1 and direction < 0) 

plotshape(buy, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small, title="Buy")
plotshape(sell, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small, title="Sell")
plotshape(closePosition, style=shape.triangledown, location=location.abovebar, color=color.purple, size=size.small, title="Sell")

