// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jinni-main

//@version=5
indicator(title = "Jinni v1", shorttitle="Jinni", overlay=true)
ema1 = input(36,title="EMA UpTrend")
shema = input(true, title="Show EMA Trend is Based On?")

length = input.int(title="Length", defval=5, minval=1)
atr = ta.rma(ta.tr(true), length) > 0.0075


sesd_ses = input.session('2100-0600')
tz_incr = input.int(0)
use_exchange = input(false)
tf = timeframe.period
tz = use_exchange ? syminfo.timezone : str.format('UTC{0}{1}', tz_incr >= 0 ? '+' : '-', math.abs(tz_incr))
syd = time(tf, sesd_ses, tz) != 0

usedEma = ta.ema(close, ema1)

cmUp = (close >= usedEma) and ((close[1] >= usedEma) and (close > close[1])) and (open >= usedEma) and not syd and atr 
cmDown = (close < usedEma) and (close[1] < usedEma and (close < close[1])) and (open < usedEma) and not syd and atr
var bool cmuflg = na
var bool cmdowflg = na

if cmUp
    cmuflg := true
    cmDown := false
if cmDown
    cmdowflg := true
    cmuflg := false

plotshape(series=cmuflg, location=location.belowbar, color=color.green, style=shape.circle, size=size.small)
plotshape(series=cmdowflg, location=location.abovebar, color=color.red, style=shape.circle, size=size.small)

barcolor(cmuflg ? color.blue : na)
barcolor(cmdowflg ? color.yellow : na)

